# Starting with splitting data

In [1]:
from pathlib import Path
import sys
from rdkit import Chem
from rdkit.Chem import AllChem, Descriptors, Draw, PandasTools, MolStandardize
from rdkit.Chem.MolStandardize import rdMolStandardize
from rdkit.Chem.Draw import IPythonConsole
IPythonConsole.ipython_useSVG=True
import rdkit.rdBase as rkrb
import rdkit.RDLogger as rkl
from IPython.display import display, display_png
from sklearn.preprocessing import FunctionTransformer
from pandas import DataFrame
import pandas as pd
import numpy as np
import logging
from tqdm import tqdm
from sklearn.model_selection import train_test_split
import pickle
import random
from rdkit import DataStructs
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import FunctionTransformer
from sklearn.linear_model import LogisticRegressionCV, LinearRegression, SGDClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.model_selection import KFold, cross_val_predict, GridSearchCV
import sklearn.metrics as metrics
from sklearn.metrics import f1_score, accuracy_score, balanced_accuracy_score, roc_auc_score, recall_score, precision_score
from sklearn.model_selection import train_test_split, cross_val_score, RepeatedStratifiedKFold
from sklearn.preprocessing import StandardScaler, FunctionTransformer
from sklearn.datasets import make_classification
from tqdm import tqdm
#import xgboost
#from xgboost import XGBRFClassifier
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix, classification_report
from rdkit import Chem
from rdkit.Chem.Scaffolds import MurckoScaffold
#import deepchem as dc
from rdkit.Chem import rdFingerprintGenerator

In [2]:
#!pip install mordred

In [3]:
#!pip install pandarallel

In [36]:
mchr1_united = pd.read_csv("chembl_set_sos1_big.csv")

/tmp/ipykernel_471808/1440510682.py:1: DtypeWarning: Columns (2,8,10,11,12,20,21,22,24,25,26,27,28,29,30,31,32,33,34,38,39,41,42,44,45,46,47,48,49,51,52,53,54,56,57,58,59,60,61,644) have mixed types. Specify dtype option on import or set low_memory=False.
  mchr1_united = pd.read_csv("chembl_set_sos1_big.csv")

In [37]:
len(mchr1_united)

5713

In [38]:
mchr1_united['class'].value_counts()

class
1    5450
0     263
Name: count, dtype: int64

In [8]:
selected_30 = PandasTools.LoadSDF('chembl_random_set.sdf',molColName='ROMol')

[21:58:47] Explicit valence for atom # 36 N, 4, is greater than permitted
[21:58:47] ERROR: Could not sanitize molecule ending on line 7298
[21:58:47] ERROR: Explicit valence for atom # 36 N, 4, is greater than permitted
[21:58:47] Explicit valence for atom # 8 O, 3, is greater than permitted
[21:58:47] ERROR: Could not sanitize molecule ending on line 14063
[21:58:47] ERROR: Explicit valence for atom # 8 O, 3, is greater than permitted
[21:58:47] Explicit valence for atom # 24 O, 3, is greater than permitted
[21:58:47] ERROR: Could not sanitize molecule ending on line 45246
[21:58:47] ERROR: Explicit valence for atom # 24 O, 3, is greater than permitted
[21:58:48] Explicit valence for atom # 9 O, 3, is greater than permitted
[21:58:48] ERROR: Could not sanitize molecule ending on line 49159
[21:58:48] ERROR: Explicit valence for atom # 9 O, 3, is greater than permitted
[21:58:48] Explicit valence for atom # 12 O, 3, is greater than permitted
[21:58:48] ERROR: Could not sanitize molecule ending on line 53546
[21:58:48] ERROR: Explicit valence for atom # 12 O, 3, is greater than permitted
[21:58:48] Explicit valence for atom # 9 N, 4, is greater than permitted
[21:58:48] ERROR: Could not sanitize molecule ending on line 55607
[21:58:48] ERROR: Explicit valence for atom # 9 N, 4, is greater than permitted
[21:58:48] Explicit valence for atom # 12 N, 4, is greater than permitted
[21:58:48] ERROR: Could not sanitize molecule ending on line 59621
[21:58:48] ERROR: Explicit valence for atom # 12 N, 4, is greater than permitted
[21:58:48] Explicit valence for atom # 44 N, 4, is greater than permitted
[21:58:48] ERROR: Could not sanitize molecule ending on line 60498
[21:58:48] ERROR: Explicit valence for atom # 44 N, 4, is greater than permitted
[21:58:48] Explicit valence for atom # 21 O, 3, is greater than permitted
[21:58:48] ERROR: Could not sanitize molecule ending on line 70545
[21:58:48] ERROR: Explicit valence for atom # 21 O, 3, is greater than permitted
[21:58:48] Explicit valence for atom # 6 O, 3, is greater than permitted
[21:58:48] ERROR: Could not sanitize molecule ending on line 90929
[21:58:48] ERROR: Explicit valence for atom # 6 O, 3, is greater than permitted
[21:58:48] Explicit valence for atom # 10 N, 4, is greater than permitted
[21:58:48] ERROR: Could not sanitize molecule ending on line 95574
[21:58:48] ERROR: Explicit valence for atom # 10 N, 4, is greater than permitted
[21:58:48] Explicit valence for atom # 31 N, 4, is greater than permitted
[21:58:48] ERROR: Could not sanitize molecule ending on line 98289
[21:58:48] ERROR: Explicit valence for atom # 31 N, 4, is greater than permitted
[21:58:48] Explicit valence for atom # 5 O, 3, is greater than permitted
[21:58:48] ERROR: Could not sanitize molecule ending on line 124514
[21:58:48] ERROR: Explicit valence for atom # 5 O, 3, is greater than permitted
[21:58:49] Explicit valence for atom # 12 O, 3, is greater than permitted
[21:58:49] ERROR: Could not sanitize molecule ending on line 144898
[21:58:49] ERROR: Explicit valence for atom # 12 O, 3, is greater than permitted
[21:58:49] Explicit valence for atom # 45 O, 3, is greater than permitted
[21:58:49] ERROR: Could not sanitize molecule ending on line 167837
[21:58:49] ERROR: Explicit valence for atom # 45 O, 3, is greater than permitted
[21:58:49] Explicit valence for atom # 1 N, 4, is greater than permitted
[21:58:49] ERROR: Could not sanitize molecule ending on line 225482
[21:58:49] ERROR: Explicit valence for atom # 1 N, 4, is greater than permitted
[21:58:50] Explicit valence for atom # 6 N, 4, is greater than permitted
[21:58:50] ERROR: Could not sanitize molecule ending on line 241031
[21:58:50] ERROR: Explicit valence for atom # 6 N, 4, is greater than permitted
[21:58:50] Explicit valence for atom # 23 O, 3, is greater than permitted
[21:58:50] ERROR: Could not sanitize molecule ending on line 246199
[21:58:50] ERROR: Explicit valence for atom # 23 O, 3, is greater than permitted
[21:58:50] Explicit valence for atom # 12 O, 3, is greater than permitted
[21:58:50] ERROR: Could not sanitize molecule ending on line 260303
[21:58:50] ERROR: Explicit valence for atom # 12 O, 3, is greater than permitted
[21:58:50] Explicit valence for atom # 17 O, 3, is greater than permitted
[21:58:50] ERROR: Could not sanitize molecule ending on line 274181
[21:58:50] ERROR: Explicit valence for atom # 17 O, 3, is greater than permitted
[21:58:50] Explicit valence for atom # 8 O, 3, is greater than permitted
[21:58:50] ERROR: Could not sanitize molecule ending on line 274815
[21:58:50] ERROR: Explicit valence for atom # 8 O, 3, is greater than permitted
[21:58:50] Explicit valence for atom # 10 N, 4, is greater than permitted
[21:58:50] ERROR: Could not sanitize molecule ending on line 281070
[21:58:50] ERROR: Explicit valence for atom # 10 N, 4, is greater than permitted
[21:58:51] Explicit valence for atom # 17 O, 3, is greater than permitted
[21:58:51] ERROR: Could not sanitize molecule ending on line 289860
[21:58:51] ERROR: Explicit valence for atom # 17 O, 3, is greater than permitted
[21:58:51] Explicit valence for atom # 3 O, 3, is greater than permitted
[21:58:51] ERROR: Could not sanitize molecule ending on line 308089
[21:58:51] ERROR: Explicit valence for atom # 3 O, 3, is greater than permitted
[21:58:51] Explicit valence for atom # 16 O, 3, is greater than permitted
[21:58:51] ERROR: Could not sanitize molecule ending on line 315210
[21:58:51] ERROR: Explicit valence for atom # 16 O, 3, is greater than permitted
[21:58:51] Explicit valence for atom # 16 N, 4, is greater than permitted
[21:58:51] ERROR: Could not sanitize molecule ending on line 321703
[21:58:51] ERROR: Explicit valence for atom # 16 N, 4, is greater than permitted
[21:58:51] Explicit valence for atom # 32 N, 4, is greater than permitted
[21:58:51] ERROR: Could not sanitize molecule ending on line 340961
[21:58:51] ERROR: Explicit valence for atom # 32 N, 4, is greater than permitted
[21:58:51] Explicit valence for atom # 0 O, 3, is greater than permitted
[21:58:51] ERROR: Could not sanitize molecule ending on line 347519
[21:58:51] ERROR: Explicit valence for atom # 0 O, 3, is greater than permitted
[21:58:51] Explicit valence for atom # 20 O, 3, is greater than permitted
[21:58:51] ERROR: Could not sanitize molecule ending on line 352883
[21:58:51] ERROR: Explicit valence for atom # 20 O, 3, is greater than permitted
[21:58:51] Explicit valence for atom # 1 O, 3, is greater than permitted
[21:58:51] ERROR: Could not sanitize molecule ending on line 357596
[21:58:51] ERROR: Explicit valence for atom # 1 O, 3, is greater than permitted
[21:58:51] Explicit valence for atom # 24 O, 3, is greater than permitted
[21:58:51] ERROR: Could not sanitize molecule ending on line 363224
[21:58:51] ERROR: Explicit valence for atom # 24 O, 3, is greater than permitted
[21:58:52] Explicit valence for atom # 3 O, 3, is greater than permitted
[21:58:52] ERROR: Could not sanitize molecule ending on line 369412
[21:58:52] ERROR: Explicit valence for atom # 3 O, 3, is greater than permitted
[21:58:52] Explicit valence for atom # 17 N, 4, is greater than permitted
[21:58:52] ERROR: Could not sanitize molecule ending on line 390178
[21:58:52] ERROR: Explicit valence for atom # 17 N, 4, is greater than permitted
[21:58:52] Explicit valence for atom # 1 O, 3, is greater than permitted
[21:58:52] ERROR: Could not sanitize molecule ending on line 417414
[21:58:52] ERROR: Explicit valence for atom # 1 O, 3, is greater than permitted
[21:58:52] Explicit valence for atom # 19 O, 3, is greater than permitted
[21:58:52] ERROR: Could not sanitize molecule ending on line 422079
[21:58:52] ERROR: Explicit valence for atom # 19 O, 3, is greater than permitted
[21:58:52] Explicit valence for atom # 30 O, 3, is greater than permitted
[21:58:52] ERROR: Could not sanitize molecule ending on line 423736
[21:58:52] ERROR: Explicit valence for atom # 30 O, 3, is greater than permitted
[21:58:52] Explicit valence for atom # 9 N, 4, is greater than permitted
[21:58:52] ERROR: Could not sanitize molecule ending on line 426329
[21:58:52] ERROR: Explicit valence for atom # 9 N, 4, is greater than permitted
[21:58:52] Explicit valence for atom # 6 N, 4, is greater than permitted
[21:58:52] ERROR: Could not sanitize molecule ending on line 430005
[21:58:52] ERROR: Explicit valence for atom # 6 N, 4, is greater than permitted
[21:58:53] Explicit valence for atom # 17 O, 3, is greater than permitted
[21:58:53] ERROR: Could not sanitize molecule ending on line 470357
[21:58:53] ERROR: Explicit valence for atom # 17 O, 3, is greater than permitted
[21:58:53] Explicit valence for atom # 13 N, 4, is greater than permitted
[21:58:53] ERROR: Could not sanitize molecule ending on line 473472
[21:58:53] ERROR: Explicit valence for atom # 13 N, 4, is greater than permitted
[21:58:53] Explicit valence for atom # 40 O, 3, is greater than permitted
[21:58:53] ERROR: Could not sanitize molecule ending on line 475807
[21:58:53] ERROR: Explicit valence for atom # 40 O, 3, is greater than permitted
[21:58:53] Explicit valence for atom # 17 O, 3, is greater than permitted
[21:58:53] ERROR: Could not sanitize molecule ending on line 503833
[21:58:53] ERROR: Explicit valence for atom # 17 O, 3, is greater than permitted
[21:58:53] Explicit valence for atom # 8 N, 4, is greater than permitted
[21:58:53] ERROR: Could not sanitize molecule ending on line 511465
[21:58:53] ERROR: Explicit valence for atom # 8 N, 4, is greater than permitted
[21:58:53] Explicit valence for atom # 1 O, 3, is greater than permitted
[21:58:53] ERROR: Could not sanitize molecule ending on line 513130
[21:58:53] ERROR: Explicit valence for atom # 1 O, 3, is greater than permitted
[21:58:53] Explicit valence for atom # 19 N, 4, is greater than permitted
[21:58:53] ERROR: Could not sanitize molecule ending on line 516597
[21:58:53] ERROR: Explicit valence for atom # 19 N, 4, is greater than permitted
[21:58:53] Explicit valence for atom # 3 O, 3, is greater than permitted
[21:58:53] ERROR: Could not sanitize molecule ending on line 517470
[21:58:53] ERROR: Explicit valence for atom # 3 O, 3, is greater than permitted
[21:58:53] Explicit valence for atom # 8 N, 4, is greater than permitted
[21:58:53] ERROR: Could not sanitize molecule ending on line 534664
[21:58:53] ERROR: Explicit valence for atom # 8 N, 4, is greater than permitted
[21:58:54] Explicit valence for atom # 9 O, 3, is greater than permitted
[21:58:54] ERROR: Could not sanitize molecule ending on line 547895
[21:58:54] ERROR: Explicit valence for atom # 9 O, 3, is greater than permitted
[21:58:54] Explicit valence for atom # 39 N, 4, is greater than permitted
[21:58:54] ERROR: Could not sanitize molecule ending on line 556896
[21:58:54] ERROR: Explicit valence for atom # 39 N, 4, is greater than permitted
[21:58:54] Explicit valence for atom # 39 N, 4, is greater than permitted
[21:58:54] ERROR: Could not sanitize molecule ending on line 562484
[21:58:54] ERROR: Explicit valence for atom # 39 N, 4, is greater than permitted
[21:58:54] Explicit valence for atom # 20 O, 3, is greater than permitted
[21:58:54] ERROR: Could not sanitize molecule ending on line 564529
[21:58:54] ERROR: Explicit valence for atom # 20 O, 3, is greater than permitted
[21:58:54] Explicit valence for atom # 22 O, 3, is greater than permitted
[21:58:54] ERROR: Could not sanitize molecule ending on line 574495
[21:58:54] ERROR: Explicit valence for atom # 22 O, 3, is greater than permitted
[21:58:54] Explicit valence for atom # 8 O, 3, is greater than permitted
[21:58:54] ERROR: Could not sanitize molecule ending on line 584538
[21:58:54] ERROR: Explicit valence for atom # 8 O, 3, is greater than permitted
[21:58:54] Explicit valence for atom # 41 O, 3, is greater than permitted
[21:58:54] ERROR: Could not sanitize molecule ending on line 593623
[21:58:54] ERROR: Explicit valence for atom # 41 O, 3, is greater than permitted
[21:58:54] Explicit valence for atom # 7 O, 3, is greater than permitted
[21:58:54] ERROR: Could not sanitize molecule ending on line 607346
[21:58:54] ERROR: Explicit valence for atom # 7 O, 3, is greater than permitted
[21:58:55] Explicit valence for atom # 1 O, 3, is greater than permitted
[21:58:55] ERROR: Could not sanitize molecule ending on line 625626
[21:58:55] ERROR: Explicit valence for atom # 1 O, 3, is greater than permitted
[21:58:55] Explicit valence for atom # 24 O, 3, is greater than permitted
[21:58:55] ERROR: Could not sanitize molecule ending on line 648589
[21:58:55] ERROR: Explicit valence for atom # 24 O, 3, is greater than permitted
[21:58:55] Explicit valence for atom # 21 N, 4, is greater than permitted
[21:58:55] ERROR: Could not sanitize molecule ending on line 649492
[21:58:55] ERROR: Explicit valence for atom # 21 N, 4, is greater than permitted
[21:58:56] Explicit valence for atom # 12 O, 3, is greater than permitted
[21:58:56] ERROR: Could not sanitize molecule ending on line 728929
[21:58:56] ERROR: Explicit valence for atom # 12 O, 3, is greater than permitted
[21:58:56] Explicit valence for atom # 26 O, 3, is greater than permitted
[21:58:56] ERROR: Could not sanitize molecule ending on line 758144
[21:58:56] ERROR: Explicit valence for atom # 26 O, 3, is greater than permitted
[21:58:57] Explicit valence for atom # 18 O, 3, is greater than permitted
[21:58:57] ERROR: Could not sanitize molecule ending on line 768747
[21:58:57] ERROR: Explicit valence for atom # 18 O, 3, is greater than permitted
[21:58:57] Explicit valence for atom # 1 O, 3, is greater than permitted
[21:58:57] ERROR: Could not sanitize molecule ending on line 780434
[21:58:57] ERROR: Explicit valence for atom # 1 O, 3, is greater than permitted
[21:58:57] Explicit valence for atom # 11 N, 4, is greater than permitted
[21:58:57] ERROR: Could not sanitize molecule ending on line 781703
[21:58:57] ERROR: Explicit valence for atom # 11 N, 4, is greater than permitted
[21:58:57] Explicit valence for atom # 17 N, 4, is greater than permitted
[21:58:57] ERROR: Could not sanitize molecule ending on line 789757
[21:58:57] ERROR: Explicit valence for atom # 17 N, 4, is greater than permitted
[21:58:57] Explicit valence for atom # 32 N, 4, is greater than permitted
[21:58:57] ERROR: Could not sanitize molecule ending on line 790544
[21:58:57] ERROR: Explicit valence for atom # 32 N, 4, is greater than permitted
[21:58:57] Explicit valence for atom # 27 N, 4, is greater than permitted
[21:58:57] ERROR: Could not sanitize molecule ending on line 795619
[21:58:57] ERROR: Explicit valence for atom # 27 N, 4, is greater than permitted
[21:58:57] Explicit valence for atom # 4 O, 3, is greater than permitted
[21:58:57] ERROR: Could not sanitize molecule ending on line 795945
[21:58:57] ERROR: Explicit valence for atom # 4 O, 3, is greater than permitted
[21:58:57] Explicit valence for atom # 6 N, 4, is greater than permitted
[21:58:57] ERROR: Could not sanitize molecule ending on line 796225
[21:58:57] ERROR: Explicit valence for atom # 6 N, 4, is greater than permitted
[21:58:57] Explicit valence for atom # 10 O, 3, is greater than permitted
[21:58:57] ERROR: Could not sanitize molecule ending on line 805607
[21:58:57] ERROR: Explicit valence for atom # 10 O, 3, is greater than permitted
[21:58:57] Explicit valence for atom # 13 N, 4, is greater than permitted
[21:58:57] ERROR: Could not sanitize molecule ending on line 808478
[21:58:57] ERROR: Explicit valence for atom # 13 N, 4, is greater than permitted
[21:58:57] Explicit valence for atom # 11 N, 4, is greater than permitted
[21:58:57] ERROR: Could not sanitize molecule ending on line 833628
[21:58:57] ERROR: Explicit valence for atom # 11 N, 4, is greater than permitted
[21:58:57] Explicit valence for atom # 8 N, 4, is greater than permitted
[21:58:57] ERROR: Could not sanitize molecule ending on line 833909
[21:58:57] ERROR: Explicit valence for atom # 8 N, 4, is greater than permitted
[21:58:58] Explicit valence for atom # 40 O, 3, is greater than permitted
[21:58:58] ERROR: Could not sanitize molecule ending on line 842682
[21:58:58] ERROR: Explicit valence for atom # 40 O, 3, is greater than permitted
[21:58:58] Explicit valence for atom # 22 O, 3, is greater than permitted
[21:58:58] ERROR: Could not sanitize molecule ending on line 856556
[21:58:58] ERROR: Explicit valence for atom # 22 O, 3, is greater than permitted
[21:58:58] Explicit valence for atom # 7 O, 3, is greater than permitted
[21:58:58] ERROR: Could not sanitize molecule ending on line 857193
[21:58:58] ERROR: Explicit valence for atom # 7 O, 3, is greater than permitted
[21:58:58] Explicit valence for atom # 8 O, 3, is greater than permitted
[21:58:58] ERROR: Could not sanitize molecule ending on line 865926
[21:58:58] ERROR: Explicit valence for atom # 8 O, 3, is greater than permitted
[21:58:58] Explicit valence for atom # 19 O, 3, is greater than permitted
[21:58:58] ERROR: Could not sanitize molecule ending on line 866248
[21:58:58] ERROR: Explicit valence for atom # 19 O, 3, is greater than permitted
[21:58:58] Explicit valence for atom # 31 N, 4, is greater than permitted
[21:58:58] ERROR: Could not sanitize molecule ending on line 871996
[21:58:58] ERROR: Explicit valence for atom # 31 N, 4, is greater than permitted
[21:58:58] Explicit valence for atom # 13 O, 3, is greater than permitted
[21:58:58] ERROR: Could not sanitize molecule ending on line 877301
[21:58:58] ERROR: Explicit valence for atom # 13 O, 3, is greater than permitted
[21:58:58] Explicit valence for atom # 1 O, 3, is greater than permitted
[21:58:58] ERROR: Could not sanitize molecule ending on line 879829
[21:58:58] ERROR: Explicit valence for atom # 1 O, 3, is greater than permitted
[21:58:58] Explicit valence for atom # 10 O, 3, is greater than permitted
[21:58:58] ERROR: Could not sanitize molecule ending on line 883300
[21:58:58] ERROR: Explicit valence for atom # 10 O, 3, is greater than permitted
[21:58:58] Explicit valence for atom # 4 O, 3, is greater than permitted
[21:58:58] ERROR: Could not sanitize molecule ending on line 886209
[21:58:58] ERROR: Explicit valence for atom # 4 O, 3, is greater than permitted
[21:58:58] Explicit valence for atom # 7 O, 3, is greater than permitted
[21:58:58] ERROR: Could not sanitize molecule ending on line 898765
[21:58:58] ERROR: Explicit valence for atom # 7 O, 3, is greater than permitted
[21:58:59] Explicit valence for atom # 15 N, 4, is greater than permitted
[21:58:59] ERROR: Could not sanitize molecule ending on line 914740
[21:58:59] ERROR: Explicit valence for atom # 15 N, 4, is greater than permitted
[21:58:59] Explicit valence for atom # 20 O, 3, is greater than permitted
[21:58:59] ERROR: Could not sanitize molecule ending on line 916299
[21:58:59] ERROR: Explicit valence for atom # 20 O, 3, is greater than permitted
[21:58:59] Explicit valence for atom # 1 O, 3, is greater than permitted
[21:58:59] ERROR: Could not sanitize molecule ending on line 921202
[21:58:59] ERROR: Explicit valence for atom # 1 O, 3, is greater than permitted
[21:58:59] Explicit valence for atom # 4 O, 3, is greater than permitted
[21:58:59] ERROR: Could not sanitize molecule ending on line 923596
[21:58:59] ERROR: Explicit valence for atom # 4 O, 3, is greater than permitted
[21:58:59] Explicit valence for atom # 14 N, 4, is greater than permitted
[21:58:59] ERROR: Could not sanitize molecule ending on line 926470
[21:58:59] ERROR: Explicit valence for atom # 14 N, 4, is greater than permitted
[21:58:59] Explicit valence for atom # 8 O, 3, is greater than permitted
[21:58:59] ERROR: Could not sanitize molecule ending on line 931520
[21:58:59] ERROR: Explicit valence for atom # 8 O, 3, is greater than permitted
[21:58:59] Explicit valence for atom # 13 O, 3, is greater than permitted
[21:58:59] ERROR: Could not sanitize molecule ending on line 964013
[21:58:59] ERROR: Explicit valence for atom # 13 O, 3, is greater than permitted

In [39]:
mchr1_united = mchr1_united[['canonical_smiles', 'standard_units', 'standard_value', 'class', 'ID']]

In [40]:
mchr1_united = mchr1_united[['canonical_smiles', 'standard_value', 'class', 'ID']]

In [ ]:
selected_30.columns = ['canonical_smiles', 'standard_type', 'value_nM', 'class', 'molecule_chembl_id']

In [42]:
#mchr1_united = mchr1_united[['canonical_smiles', 'standard_type', 'standard_value', 'class', 'ID']]
selected_30 = selected_30.rename(columns={'molecule_chembl_id': 'ID'})
mchr1_united = mchr1_united.rename(columns={'standard_value': 'value_nM'})

In [43]:
selected_30 = selected_30[['canonical_smiles', 'value_nM', 'class', 'ID']]

In [44]:
selected_30 = selected_30.sample(frac=1).reset_index(drop=True)

In [45]:
n_subsets = 10
subsets = [selected_30.iloc[i::n_subsets].reset_index(drop=True) for i in range(n_subsets)]
subsets[0]

,canonical_smiles,value_nM,class,ID
0,CCOC(=O)C1=C(C)NC(=O)N(CCC(=O)NNC(=S)Nc2ccccc2...,Random,0,test_outputs/chembl_inactive_pdb/molecule_2984...
1,CC(C)(C)OC(=O)N[C@H]1COCCC/C=C\[C@@H]2C[C@@]2(...,Random,0,test_outputs/chembl_inactive_pdb/molecule_2736...
2,CS(=O)(=O)N(Cc1ccc(C(=O)NN=C2CCCC2)cc1)c1ccccc1,Random,0,test_outputs/chembl_inactive_pdb/molecule_1525...
3,COC(=O)c1cn(NC(=O)c2cc([N+](=O)[O-])ccc2F)c(=O...,Random,0,test_outputs/chembl_inactive_pdb/molecule_2572...
4,CC1(C)C(=O)OC(/C=C\c2cccc([N+](=O)[O-])c2)C(C)...,Random,0,test_outputs/chembl_inactive_pdb/molecule_2121...
...,...,...,...,...
2940,CC(C)Nc1ccc2cnn(-c3cncc(-c4csc(C(=O)O)c4)n3)c2c1,Random,0,test_outputs/chembl_inactive_pdb/molecule_3384...
2941,CO[C@H]1CC[C@H](CC(=O)N[C@H]2CC[C@H](CCN3CCC(c...,Random,0,test_outputs/chembl_inactive_pdb/molecule_7353...
2942,COc1cc2nccc(Oc3ccc(NC(=O)c4c(N5CCN(C)CC5)ccn(-...,Random,0,test_outputs/chembl_inactive_pdb/molecule_1303...
2943,CN1C(=O)c2c(ncn2CC(=O)Nc2nc(-c3ccc(C(C)(C)C)cc...,Random,0,test_outputs/chembl_inactive_pdb/molecule_2906...
2944,OC[C@@H](Nc1ncnc2oc(-c3ccccc3)c(-c3ccoc3)c12)c...,Random,0,test_outputs/chembl_inactive_pdb/molecule_2699...

In [46]:
subsets = [pd.concat([mchr1_united, i], ignore_index=True) for i in subsets]

In [47]:
subsets[0]

,canonical_smiles,value_nM,class,ID
0,CC[C@H](C)[C@H](NC(=O)CN1C/C=C\CCC(=O)N[C@@H](...,25000.0,0,CHEMBL2086797
1,N[C@@H](Cc1c[nH]c2ccccc12)C(=O)N1CCC2(CC1)CN(C...,37300.0,0,CHEMBL4160864
2,N[C@@H](Cc1c[nH]c2ccccc12)C(=O)N1CC2(CCN(Cc3c[...,100000.0,0,CHEMBL4168801
3,N[C@@H](Cc1c[nH]c2ccccc12)C(=O)NCC1CCN(Cc2c[nH...,13300.0,0,CHEMBL4171085
4,N[C@@H](Cc1c[nH]c2cc(Cl)ccc12)C(=O)NC1CCN(Cc2c...,1400.0,1,CHEMBL4160484
...,...,...,...,...
8653,CC(C)Nc1ccc2cnn(-c3cncc(-c4csc(C(=O)O)c4)n3)c2c1,Random,0,test_outputs/chembl_inactive_pdb/molecule_3384...
8654,CO[C@H]1CC[C@H](CC(=O)N[C@H]2CC[C@H](CCN3CCC(c...,Random,0,test_outputs/chembl_inactive_pdb/molecule_7353...
8655,COc1cc2nccc(Oc3ccc(NC(=O)c4c(N5CCN(C)CC5)ccn(-...,Random,0,test_outputs/chembl_inactive_pdb/molecule_1303...
8656,CN1C(=O)c2c(ncn2CC(=O)Nc2nc(-c3ccc(C(C)(C)C)cc...,Random,0,test_outputs/chembl_inactive_pdb/molecule_2906...
8657,OC[C@@H](Nc1ncnc2oc(-c3ccccc3)c(-c3ccoc3)c12)c...,Random,0,test_outputs/chembl_inactive_pdb/molecule_2699...

In [48]:
with open('subsets_10_big.pkl', 'wb') as file:
    pickle.dump(subsets, file)

In [49]:
with open('subsets_10_big.pkl', 'rb') as file:
    subsets = pickle.load(file)

In [50]:
selected_30.columns

Index(['canonical_smiles', 'value_nM', 'class', 'ID'], dtype='object')

In [51]:
mchr1_united.columns

Index(['canonical_smiles', 'value_nM', 'class', 'ID'], dtype='object')

# Training on the WHOLE set

In [52]:
#! pip install ipywidgets

In [53]:
set = pd.concat([mchr1_united, selected_30], ignore_index=True)

In [54]:
len(set)

35157

In [60]:
set['class'] = set['class'].astype(int)

In [61]:
set['Scaffold'] = set['canonical_smiles'].apply(lambda x: Chem.MolToSmiles(MurckoScaffold.GetScaffoldForMol(Chem.MolFromSmiles(x))))

In [62]:
def train_test_onescaffold_split(df, test_size1 = 0.2):
    grouped = df.groupby('Scaffold')
    shuffled_groups = grouped.groups.keys()
    shuffled_groups = list(shuffled_groups)
    random.shuffle(shuffled_groups)
    train_scaffolds, test_scaffolds = train_test_split(shuffled_groups, test_size=test_size1, random_state=42)
    train_mask = df['Scaffold'].isin(train_scaffolds)
    test_mask = df['Scaffold'].isin(test_scaffolds)
    train_df = df[train_mask]
    test_df = df[test_mask]
    return train_df, test_df

In [63]:
train_df, test_df = train_test_onescaffold_split(set)

In [64]:
train_df['class'].value_counts()

class
0    23764
1     4451
Name: count, dtype: int64

In [65]:
test_df['class'].value_counts()

class
0    5943
1     999
Name: count, dtype: int64

# Features calculation

In [66]:
def calc_morgan_fingerprints(mol, r=2, nBits=512, errors_as_zeros=True):
    try:
        fpgen = rdFingerprintGenerator.GetMorganGenerator(radius=r, fpSize=nBits)
        fp = fpgen.GetFingerprint(mol)
        arr = np.zeros((nBits,), dtype=np.int32)
        DataStructs.ConvertToNumpyArray(fp, arr)
        return arr.astype(np.float32)
    except:
        return np.NaN if not errors_as_zeros else np.zeros((nBits,), dtype=np.float32)

In [67]:
from mordred import Calculator, descriptors, is_missing
calc = Calculator(descriptors, ignore_3D=False)

In [68]:

def calc_mordred_descriptors(mol, l=1826, errors_as_zeros=True):
    try:
        result = calc(mol)
        desc_list = [r if not is_missing(r) else 0 for r in result]
        np_arr = np.array(desc_list)
        return np_arr
    except:
        return np.NaN if not errors_as_zeros else np.zeros((l,), dtype=np.float32)

In [69]:
from rdkit import Chem
from rdkit.Chem import MACCSkeys, DataStructs
import numpy as np

In [70]:
def calc_MACCS_fingerprints(mol, nBits=167, errors_as_zeros=True):
    try:
        fp = MACCSkeys.GenMACCSKeys(mol)
        arr = np.zeros((nBits,), dtype=np.int32)
        DataStructs.ConvertToNumpyArray(fp, arr)
        return arr.astype(np.float32)
    except:
        return np.NaN if not errors_as_zeros else np.zeros((nBits,), dtype=np.float32)

In [71]:
from pandarallel import pandarallel
pandarallel.initialize(progress_bar=True)

INFO: Pandarallel will run on 6 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.

In [72]:
from tqdm.auto import tqdm
tqdm.pandas()

In [73]:
train_df['ROMol'] = train_df['canonical_smiles'].progress_apply(Chem.MolFromSmiles)

  0%|          | 0/28215 [00:00<?, ?it/s]

/tmp/ipykernel_471808/2559692629.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['ROMol'] = train_df['canonical_smiles'].progress_apply(Chem.MolFromSmiles)

In [74]:
train_df['MorganFP'] = train_df['ROMol'].parallel_apply(calc_morgan_fingerprints)

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=4703), Label(value='0 / 4703'))), …

/tmp/ipykernel_471808/4049408413.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['MorganFP'] = train_df['ROMol'].parallel_apply(calc_morgan_fingerprints)

In [75]:
train_df['MACCSFP'] = train_df['ROMol'].parallel_apply(calc_MACCS_fingerprints)

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=4703), Label(value='0 / 4703'))), …

/tmp/ipykernel_471808/753497247.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['MACCSFP'] = train_df['ROMol'].parallel_apply(calc_MACCS_fingerprints)

In [76]:
sum(train_df['MorganFP']) # Review that Morgan FP vector is not null

array([ 4391.,  9543.,  3894.,  3516.,  8213.,  2542.,  1463.,  1364.,
        2902.,  1573.,  2882.,  4344.,  1408.,  2379.,  3107.,  7640.,
        1718.,   816.,   844.,  3324.,  1209.,  1900.,  1456.,  1242.,
        1074.,  2051.,  1590.,  1089.,  2717.,  4222.,   710.,  2759.,
        1467., 20297.,  1690.,  1033.,  7760.,  3868.,  1514.,  2897.,
        3183.,  3250.,  5871.,  2043.,  1655.,  4091.,  3870.,  1004.,
         707.,  5300.,  3083.,   779.,  1639.,  3286.,   780.,   678.,
        1905.,   701.,  1868.,  1318.,   856.,  3189.,  1789.,  3166.,
       18975.,  2648.,  2605.,  3063.,  2591.,  2707.,   630.,  2017.,
        2514.,  5937.,  2984.,  2043.,  2219.,  3275.,  1080.,  2237.,
       18807.,  1751.,  1566.,  1590.,  1943.,  1086.,  1957.,   975.,
        1632.,   605.,  8812.,  3859.,  3057.,   792.,  3918.,  2324.,
        1084.,  1820.,  2225.,  1268.,  1402.,  1397.,  5396.,   788.,
        2479.,  1104.,  1182.,  1285.,  1822.,  2132.,  1836.,  3423.,
        3224.,  1113.,  6295.,  2102.,  2277.,  3101.,  1407.,  4142.,
         972.,  7661.,  3458.,  1624.,   796.,  2445.,  2178.,  1323.,
       15447.,  3225.,  2209.,  1644.,   948.,  2379.,  2709.,  1344.,
        5697.,  1000., 22890.,  2511.,  4763.,  1492.,  1423.,  1187.,
        9836.,  1887.,  1074.,  9553.,   999.,  1209.,   895.,  1062.,
        1959.,  1244.,  1078.,  3561.,  1188.,  3320.,  1398.,   846.,
        3948.,  2885.,  4011.,  5977.,  1007.,  1914.,  1121.,  2776.,
        2159.,   746.,   805.,  1408.,  3401.,  2393.,   923., 12984.,
         948.,  1678.,  3720.,   965.,  1868.,  2578.,  4298., 11475.,
        2431.,  1079.,  8841.,  4812.,  2078.,   839.,  1093.,  4092.,
        1380.,  1881.,  1313.,  1587.,  4156.,  4633.,  1286.,   844.,
        2684.,  1744.,  4720.,  3523.,  1879.,   926.,  3532.,  1839.,
        1049.,  4065.,  1021.,  1886.,  4172.,  2249., 26086.,   873.,
        3938.,  1464.,  8162.,  3960.,   917.,  1950.,  2672.,  1051.,
        3216.,  1867.,  1623.,  4729.,   828.,  3142.,  1159.,  4285.,
        1807.,  5023.,   537.,  4146.,  2138.,  4247.,  1879.,  2506.,
        1546.,  2461.,  2011.,  1493.,   663.,  1635.,  2348.,  3224.,
        2369.,  3220.,  3705.,  1453.,  1774.,   968.,   898.,  8007.,
        1254.,  1099.,  1401.,  1934.,  1592.,  1605.,  2769.,  1295.,
        1393.,  1201.,   907.,  1735.,  3115.,  3243.,  1397.,  2544.,
        3514.,  1908.,  2296.,  3963.,  2026.,  1013.,  2493.,   816.,
        4565.,  1880.,  1960.,  7441.,  1919.,  2994.,  3019.,  2377.,
        3841.,  4676.,  3032.,  1358.,  1477.,   899.,  5988., 19358.,
        1962.,  4538.,   965.,  1103.,   821., 10977.,  1012.,  1126.,
        4025.,  1779.,   869.,  1271.,  1116.,  1259.,  4992.,  2270.,
         730.,  1462.,  9640.,  1377.,  1837.,  1863.,  2052., 11772.,
        2628.,  1059.,  4598.,  3459.,  1432.,  3474.,  1732.,  3874.,
        1399.,  6291.,  5543.,  3481.,   978.,  8652.,   831.,  2957.,
         856., 27632.,  1832.,   901.,  2113.,  3151.,  1690.,  3089.,
        2073.,  1517.,   932.,   805.,  1216.,  1204.,  3783.,  1375.,
        4695.,   735.,  1167.,   898., 28026.,  1254.,  2413.,   721.,
        2505.,  6203.,  1356., 16936.,   954.,   956.,  4734.,  3449.,
         935.,  5902.,  1038.,  1774.,  2081.,  1280.,  2759.,  3475.,
        1919.,   886., 19761.,  1422.,  1469., 18394.,   923.,  2517.,
        5393.,  2322.,  3478.,  2799.,   781.,  9076.,  1378.,  1040.,
       10216.,  2236.,  2440.,   703.,  1167.,  1393.,  2109.,   994.,
        2708.,  1865.,   975.,  2572.,  1065.,  1459.,  1700.,  3928.,
         723.,  1056.,  3285.,   736.,  2236.,  2095., 20441.,  2967.,
        1572.,  2244.,  1108.,  3457.,  3420.,  2448.,  1650., 19632.,
         907.,  1623.,   877.,  1283., 10472.,  5368.,  1790.,  1646.,
        1742.,  3029.,  4038.,  2091.,  1619.,  1577.,  4644.,  1024.,
        1510.,  2623.,  2005.,   818.,  3848.,   822.,  2707.,   894.,
        3619.,  3177.,   548.,  2073.,  3794.,  1693.,  2092.,  3354.,
       12201.,  1579.,  3365.,  1257.,   548.,  1428.,  5022.,  2734.,
        4022.,  1049.,  1216.,   623.,  3499.,  1257.,  1218.,  2215.,
        2581.,  4607.,  1609.,  1545.,  1132.,  1713.,  1055.,   944.,
        2248.,  1488.,  2849.,  1246.,  3546.,  1690.,  4937.,  1189.,
        1123.,  2328.,  1656.,  1996.,  3348.,  1263.,  1925.,   582.,
        1357.,  3051.,  1522.,  1120.,  1356.,  1307.,  2448.,  1474.,
        2159.,  2810.,  1611., 15219.,   972.,  1867.,   874.,  6514.],
      dtype=float32)

In [77]:
from scipy.sparse import csr_matrix

In [78]:
X_train = csr_matrix(np.vstack(train_df['MorganFP'].values))

In [79]:
y_train = train_df['class'].values

In [80]:
with open('fps_morgans_big.pkl', 'wb') as file:
    pickle.dump(X_train, file)

In [109]:
# ! pip install xgboost

In [110]:
 #! pip install optuna

In [81]:
import xgboost as xgb

In [82]:
dtrain = xgb.DMatrix(X_train, label=y_train)
dtrain.num_row(), dtrain.num_col()

(28215, 512)

In [83]:
prevalence = train_df['class'].astype(int).sum() / train_df['class'].astype(int).shape[0]
print(f'prevalence is {prevalence:.5f}')

prevalence is 0.15775

In [84]:
import optuna


def objective(trial):
    max_depth = trial.suggest_int('max_depth', 2, 6)
    gamma = trial.suggest_loguniform('gamma', 0.01, 10)
    colsample_bytree = trial.suggest_uniform('colsample_bytree', 0.1, 0.9)

    params = {'max_depth': max_depth,
          'eta': 0.05,
          'objective': 'binary:logistic',
          'eval_metric':['auc', 'map', 'logloss'], # acc, bac, f1_score, precission and recall are not supported in eval_metrics
          'tree_method': 'hist',
          'gamma': gamma,
          'colsample_bytree': colsample_bytree,
          'subsample': 0.5,
          'nthread': 8,
          'base_score': prevalence}

    res = xgb.cv(params,
                 dtrain,
                 num_boost_round=2000,
                 verbose_eval=False,
                 early_stopping_rounds=20,
                 nfold=5,
                 seed=113,
                 shuffle=True)

    metric = res['test-map-mean'].max()
    return metric

In [85]:
study_name = 'xgboost_fingerprints_big'
study = optuna.create_study(study_name=study_name,
                          storage=f'sqlite:///{study_name}.db',
                          direction='maximize',
                          load_if_exists=True)

[I 2026-03-15 22:16:40,295] A new study created in RDB with name: xgboost_fingerprints_big

In [86]:
study.optimize(objective, n_trials=10)

/tmp/ipykernel_471808/3326202407.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  gamma = trial.suggest_loguniform('gamma', 0.01, 10)
/tmp/ipykernel_471808/3326202407.py:7: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  colsample_bytree = trial.suggest_uniform('colsample_bytree', 0.1, 0.9)
[I 2026-03-15 22:17:07,350] Trial 0 finished with value: 1.0 and parameters: {'max_depth': 5, 'gamma': 0.013837560607443624, 'colsample_bytree': 0.846783286019613}. Best is trial 0 with value: 1.0.
[I 2026-03-15 22:17:23,881] Trial 1 finished with value: 1.0 and parameters: {'max_depth': 5, 'gamma': 0.12860138766285287, 'colsample_bytree': 0.21791859661345292}. Best is trial 0 with value: 1.0.
[I 2026-03-15 22:17:46,570] Trial 2 finished with value: 1.0 and parameters: {'max_depth': 4, 'gamma': 0.08868607917238486, 'colsample_bytree': 0.16345096486908012}. Best is trial 0 with value: 1.0.
[I 2026-03-15 22:17:59,779] Trial 3 finished with value: 1.0 and parameters: {'max_depth': 6, 'gamma': 0.7989426410854602, 'colsample_bytree': 0.8891330825955931}. Best is trial 0 with value: 1.0.
[I 2026-03-15 22:18:15,416] Trial 4 finished with value: 1.0 and parameters: {'max_depth': 4, 'gamma': 0.2075079399924525, 'colsample_bytree': 0.8022878927852248}. Best is trial 0 with value: 1.0.
[I 2026-03-15 22:18:41,051] Trial 5 finished with value: 1.0 and parameters: {'max_depth': 4, 'gamma': 4.00049142702329, 'colsample_bytree': 0.636020161978228}. Best is trial 0 with value: 1.0.
[I 2026-03-15 22:19:05,205] Trial 6 finished with value: 1.0 and parameters: {'max_depth': 3, 'gamma': 0.03711689771856496, 'colsample_bytree': 0.227190600083721}. Best is trial 0 with value: 1.0.
[I 2026-03-15 22:19:41,503] Trial 7 finished with value: 1.0 and parameters: {'max_depth': 2, 'gamma': 0.09482750208096408, 'colsample_bytree': 0.7460694688361391}. Best is trial 0 with value: 1.0.
[I 2026-03-15 22:20:00,800] Trial 8 finished with value: 1.0 and parameters: {'max_depth': 3, 'gamma': 0.30524452258102924, 'colsample_bytree': 0.7398722568718797}. Best is trial 0 with value: 1.0.
[I 2026-03-15 22:20:14,186] Trial 9 finished with value: 1.0 and parameters: {'max_depth': 6, 'gamma': 0.15816169358255283, 'colsample_bytree': 0.6218546266543147}. Best is trial 0 with value: 1.0.

In [87]:
study.best_params

{'max_depth': 5,
 'gamma': 0.013837560607443624,
 'colsample_bytree': 0.846783286019613}

In [88]:
study.best_value

1.0

In [89]:
with open('XGB_best_params_big.pkl', 'wb') as file:
    pickle.dump(study, file)

In [90]:
with open('XGB_best_params_big.pkl', 'rb') as file:
    study = pickle.load(file)

In [91]:
study

In [92]:
from sklearn.model_selection import train_test_split

X_t, X_val, y_t, y_val = train_test_split(X_train, y_train, test_size=0.2)

dt = xgb.DMatrix(X_t, label=y_t)
dval = xgb.DMatrix(X_val, label=y_val)

params = {
          'max_depth': study.best_params['max_depth'],
          'eta': 0.05,
          'objective': 'binary:logistic',
          'eval_metric':['auc', 'logloss', 'map'],
          'tree_method': 'hist',
          'gamma': study.best_params['gamma'],
          'colsample_bytree': study.best_params['colsample_bytree'],
          'subsample': 0.5,
          'nthread': 8,
          'base_score': prevalence
}

bst = xgb.train(params,
                dt,
                num_boost_round=500,
                verbose_eval=10,
                early_stopping_rounds=20,
                evals=[(dtrain, 'train'), (dval, 'val')])

bst.save_model('generalXGB_big.model')

[0]	train-auc:0.98519	train-logloss:0.39392	train-map:1.00000	val-auc:0.98596	val-logloss:0.39189	val-map:0.96777
[10]	train-auc:0.99707	train-logloss:0.20212	train-map:1.00000	val-auc:0.99709	val-logloss:0.20097	val-map:1.00000
[20]	train-auc:0.99814	train-logloss:0.12584	train-map:1.00000	val-auc:0.99766	val-logloss:0.12512	val-map:1.00000
[21]	train-auc:0.99823	train-logloss:0.12052	train-map:1.00000	val-auc:0.99767	val-logloss:0.11986	val-map:1.00000

/tmp/ipykernel_471808/2525310426.py:28: UserWarning: [22:21:43] WARNING: /__w/xgboost/xgboost/src/c_api/c_api.cc:1573: Saving model in the UBJSON format as default.  You can use a file extension: `json` or `ubj` to choose between formats.
  bst.save_model('generalXGB_big.model')

In [93]:
test_df['ROMol'] = test_df['canonical_smiles'].progress_apply(Chem.MolFromSmiles)
test_df['MorganFP'] = test_df['ROMol'].parallel_apply(calc_morgan_fingerprints)

  0%|          | 0/6942 [00:00<?, ?it/s]

/tmp/ipykernel_471808/3682329790.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['ROMol'] = test_df['canonical_smiles'].progress_apply(Chem.MolFromSmiles)

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=1157), Label(value='0 / 1157'))), …

/tmp/ipykernel_471808/3682329790.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['MorganFP'] = test_df['ROMol'].parallel_apply(calc_morgan_fingerprints)

In [94]:
X_test = csr_matrix(np.vstack(test_df['MorganFP'].values))

In [95]:
y_test = test_df['class'].values

In [96]:
test_df['class'] = test_df['class'].astype(int)

/tmp/ipykernel_471808/499460510.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['class'] = test_df['class'].astype(int)

In [97]:
from sklearn.model_selection import train_test_split

#X_t, X_val, y_t, y_val = train_test_split(X_train, y_train, test_size=0.2)

dt = xgb.DMatrix(X_train, label=y_train)
#dval = xgb.DMatrix(X_test, label=y_test)

params = {
          'max_depth': study.best_params['max_depth'],
          'eta': 0.05,
          'objective': 'binary:logistic',
          'eval_metric':['auc', 'logloss', 'map'],
          'tree_method': 'hist',
          'gamma': study.best_params['gamma'],
          'colsample_bytree': study.best_params['colsample_bytree'],
          'subsample': 0.5,
          'nthread': 8,
          'base_score': prevalence
}

bst = xgb.train(params,
                dt,
                num_boost_round=500,
                verbose_eval=10)

bst.save_model('general_all_XGB_big.model')

/tmp/ipykernel_471808/332217036.py:26: UserWarning: [22:22:57] WARNING: /__w/xgboost/xgboost/src/c_api/c_api.cc:1573: Saving model in the UBJSON format as default.  You can use a file extension: `json` or `ubj` to choose between formats.
  bst.save_model('general_all_XGB_big.model')

In [98]:
test_df['ROMol'] = test_df['canonical_smiles'].progress_apply(Chem.MolFromSmiles)
test_df['MorganFP'] = test_df['ROMol'].parallel_apply(calc_morgan_fingerprints)

  0%|          | 0/6942 [00:00<?, ?it/s]

/tmp/ipykernel_471808/3682329790.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['ROMol'] = test_df['canonical_smiles'].progress_apply(Chem.MolFromSmiles)

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=1157), Label(value='0 / 1157'))), …

/tmp/ipykernel_471808/3682329790.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['MorganFP'] = test_df['ROMol'].parallel_apply(calc_morgan_fingerprints)

In [99]:
X_test = csr_matrix(np.vstack(test_df['MorganFP'].values))

In [100]:
y_test = test_df['class'].values

In [101]:
from sklearn.metrics import roc_auc_score, precision_score, confusion_matrix, f1_score

dtest = xgb.DMatrix(X_test)
y_pred = bst.predict(dtest)
auc = roc_auc_score(y_test, y_pred)
print(f'auc is {auc:.5f}')

for th in np.arange(0.0, 1.0, 0.01):
    y_pred_binary = (y_pred > th).astype(int)
    cm = confusion_matrix(y_test, y_pred_binary)
    tp, fp, fn, tn = cm[1, 1], cm[0, 1], cm[1, 0], cm[0, 0]
    precision = precision_score(y_test, y_pred > th)
    f1 = f1_score(y_test, y_pred > th)
    print(f'th: {th:.3f}\t tp: {tp}\t tn: {tn}\tfp: {fp}\tfn: {fn}\t prec: {precision:.4f} \t f1_score: {f1:.4f}')

auc is 0.99899
th: 0.000	 tp: 999	 tn: 0	fp: 5943	fn: 0	 prec: 0.1439 	 f1_score: 0.2516
th: 0.010	 tp: 996	 tn: 5842	fp: 101	fn: 3	 prec: 0.9079 	 f1_score: 0.9504
th: 0.020	 tp: 996	 tn: 5884	fp: 59	fn: 3	 prec: 0.9441 	 f1_score: 0.9698
th: 0.030	 tp: 995	 tn: 5897	fp: 46	fn: 4	 prec: 0.9558 	 f1_score: 0.9755
th: 0.040	 tp: 995	 tn: 5902	fp: 41	fn: 4	 prec: 0.9604 	 f1_score: 0.9779
th: 0.050	 tp: 995	 tn: 5907	fp: 36	fn: 4	 prec: 0.9651 	 f1_score: 0.9803
th: 0.060	 tp: 995	 tn: 5910	fp: 33	fn: 4	 prec: 0.9679 	 f1_score: 0.9817
th: 0.070	 tp: 995	 tn: 5914	fp: 29	fn: 4	 prec: 0.9717 	 f1_score: 0.9837
th: 0.080	 tp: 995	 tn: 5914	fp: 29	fn: 4	 prec: 0.9717 	 f1_score: 0.9837
th: 0.090	 tp: 995	 tn: 5914	fp: 29	fn: 4	 prec: 0.9717 	 f1_score: 0.9837
th: 0.100	 tp: 995	 tn: 5916	fp: 27	fn: 4	 prec: 0.9736 	 f1_score: 0.9847
th: 0.110	 tp: 995	 tn: 5916	fp: 27	fn: 4	 prec: 0.9736 	 f1_score: 0.9847
th: 0.120	 tp: 995	 tn: 5918	fp: 25	fn: 4	 prec: 0.9755 	 f1_score: 0.9856
th: 0.130	 tp: 994	 tn: 5919	fp: 24	fn: 5	 prec: 0.9764 	 f1_score: 0.9856
th: 0.140	 tp: 994	 tn: 5920	fp: 23	fn: 5	 prec: 0.9774 	 f1_score: 0.9861
th: 0.150	 tp: 994	 tn: 5920	fp: 23	fn: 5	 prec: 0.9774 	 f1_score: 0.9861
th: 0.160	 tp: 994	 tn: 5920	fp: 23	fn: 5	 prec: 0.9774 	 f1_score: 0.9861
th: 0.170	 tp: 993	 tn: 5921	fp: 22	fn: 6	 prec: 0.9783 	 f1_score: 0.9861
th: 0.180	 tp: 993	 tn: 5921	fp: 22	fn: 6	 prec: 0.9783 	 f1_score: 0.9861
th: 0.190	 tp: 993	 tn: 5921	fp: 22	fn: 6	 prec: 0.9783 	 f1_score: 0.9861
th: 0.200	 tp: 993	 tn: 5922	fp: 21	fn: 6	 prec: 0.9793 	 f1_score: 0.9866
th: 0.210	 tp: 993	 tn: 5922	fp: 21	fn: 6	 prec: 0.9793 	 f1_score: 0.9866
th: 0.220	 tp: 993	 tn: 5923	fp: 20	fn: 6	 prec: 0.9803 	 f1_score: 0.9871
th: 0.230	 tp: 993	 tn: 5923	fp: 20	fn: 6	 prec: 0.9803 	 f1_score: 0.9871
th: 0.240	 tp: 993	 tn: 5924	fp: 19	fn: 6	 prec: 0.9812 	 f1_score: 0.9876
th: 0.250	 tp: 993	 tn: 5925	fp: 18	fn: 6	 prec: 0.9822 	 f1_score: 0.9881
th: 0.260	 tp: 992	 tn: 5925	fp: 18	fn: 7	 prec: 0.9822 	 f1_score: 0.9876
th: 0.270	 tp: 992	 tn: 5925	fp: 18	fn: 7	 prec: 0.9822 	 f1_score: 0.9876
th: 0.280	 tp: 992	 tn: 5925	fp: 18	fn: 7	 prec: 0.9822 	 f1_score: 0.9876
th: 0.290	 tp: 992	 tn: 5925	fp: 18	fn: 7	 prec: 0.9822 	 f1_score: 0.9876
th: 0.300	 tp: 992	 tn: 5926	fp: 17	fn: 7	 prec: 0.9832 	 f1_score: 0.9880
th: 0.310	 tp: 992	 tn: 5926	fp: 17	fn: 7	 prec: 0.9832 	 f1_score: 0.9880
th: 0.320	 tp: 992	 tn: 5929	fp: 14	fn: 7	 prec: 0.9861 	 f1_score: 0.9895
th: 0.330	 tp: 992	 tn: 5929	fp: 14	fn: 7	 prec: 0.9861 	 f1_score: 0.9895
th: 0.340	 tp: 992	 tn: 5929	fp: 14	fn: 7	 prec: 0.9861 	 f1_score: 0.9895
th: 0.350	 tp: 992	 tn: 5929	fp: 14	fn: 7	 prec: 0.9861 	 f1_score: 0.9895
th: 0.360	 tp: 991	 tn: 5929	fp: 14	fn: 8	 prec: 0.9861 	 f1_score: 0.9890
th: 0.370	 tp: 991	 tn: 5929	fp: 14	fn: 8	 prec: 0.9861 	 f1_score: 0.9890
th: 0.380	 tp: 991	 tn: 5929	fp: 14	fn: 8	 prec: 0.9861 	 f1_score: 0.9890
th: 0.390	 tp: 990	 tn: 5929	fp: 14	fn: 9	 prec: 0.9861 	 f1_score: 0.9885
th: 0.400	 tp: 990	 tn: 5929	fp: 14	fn: 9	 prec: 0.9861 	 f1_score: 0.9885
th: 0.410	 tp: 990	 tn: 5929	fp: 14	fn: 9	 prec: 0.9861 	 f1_score: 0.9885
th: 0.420	 tp: 990	 tn: 5931	fp: 12	fn: 9	 prec: 0.9880 	 f1_score: 0.9895
th: 0.430	 tp: 990	 tn: 5931	fp: 12	fn: 9	 prec: 0.9880 	 f1_score: 0.9895
th: 0.440	 tp: 990	 tn: 5931	fp: 12	fn: 9	 prec: 0.9880 	 f1_score: 0.9895
th: 0.450	 tp: 990	 tn: 5931	fp: 12	fn: 9	 prec: 0.9880 	 f1_score: 0.9895
th: 0.460	 tp: 990	 tn: 5932	fp: 11	fn: 9	 prec: 0.9890 	 f1_score: 0.9900
th: 0.470	 tp: 990	 tn: 5932	fp: 11	fn: 9	 prec: 0.9890 	 f1_score: 0.9900
th: 0.480	 tp: 990	 tn: 5932	fp: 11	fn: 9	 prec: 0.9890 	 f1_score: 0.9900
th: 0.490	 tp: 989	 tn: 5932	fp: 11	fn: 10	 prec: 0.9890 	 f1_score: 0.9895
th: 0.500	 tp: 989	 tn: 5932	fp: 11	fn: 10	 prec: 0.9890 	 f1_score: 0.9895
th: 0.510	 tp: 989	 tn: 5932	fp: 11	fn: 10	 prec: 0.9890 	 f1_score: 0.9895
th: 0.520	 tp: 989	 tn: 5932	fp: 11	fn: 10	 prec: 0.9890 	 f1_score: 0.9895
th: 0.530	 tp: 989	 tn: 5932	fp: 11	fn: 10	 prec: 0.9890 	 f1_score: 0.9895
th: 0.540	 tp: 989	 tn: 5932	fp: 11	fn: 10	 prec: 0.9890 	 f1_score: 0.9895
th: 0.550	 tp: 988	 tn: 5932	fp: 11	fn: 11	 prec: 0.9890 	 f1_score: 0.9890
th: 0.560	 tp: 988	 tn: 5933	fp: 10	fn: 11	 prec: 0.9900 	 f1_score: 0.9895
th: 0.570	 tp: 988	 tn: 5933	fp: 10	fn: 11	 prec: 0.9900 	 f1_score: 0.9895
th: 0.580	 tp: 988	 tn: 5933	fp: 10	fn: 11	 prec: 0.9900 	 f1_score: 0.9895
th: 0.590	 tp: 988	 tn: 5933	fp: 10	fn: 11	 prec: 0.9900 	 f1_score: 0.9895
th: 0.600	 tp: 988	 tn: 5933	fp: 10	fn: 11	 prec: 0.9900 	 f1_score: 0.9895
th: 0.610	 tp: 987	 tn: 5933	fp: 10	fn: 12	 prec: 0.9900 	 f1_score: 0.9890
th: 0.620	 tp: 986	 tn: 5933	fp: 10	fn: 13	 prec: 0.9900 	 f1_score: 0.9885
th: 0.630	 tp: 985	 tn: 5933	fp: 10	fn: 14	 prec: 0.9899 	 f1_score: 0.9880
th: 0.640	 tp: 984	 tn: 5933	fp: 10	fn: 15	 prec: 0.9899 	 f1_score: 0.9875
th: 0.650	 tp: 984	 tn: 5933	fp: 10	fn: 15	 prec: 0.9899 	 f1_score: 0.9875
th: 0.660	 tp: 982	 tn: 5933	fp: 10	fn: 17	 prec: 0.9899 	 f1_score: 0.9864
th: 0.670	 tp: 982	 tn: 5933	fp: 10	fn: 17	 prec: 0.9899 	 f1_score: 0.9864
th: 0.680	 tp: 982	 tn: 5933	fp: 10	fn: 17	 prec: 0.9899 	 f1_score: 0.9864
th: 0.690	 tp: 982	 tn: 5933	fp: 10	fn: 17	 prec: 0.9899 	 f1_score: 0.9864
th: 0.700	 tp: 982	 tn: 5933	fp: 10	fn: 17	 prec: 0.9899 	 f1_score: 0.9864
th: 0.710	 tp: 981	 tn: 5933	fp: 10	fn: 18	 prec: 0.9899 	 f1_score: 0.9859
th: 0.720	 tp: 980	 tn: 5933	fp: 10	fn: 19	 prec: 0.9899 	 f1_score: 0.9854
th: 0.730	 tp: 980	 tn: 5933	fp: 10	fn: 19	 prec: 0.9899 	 f1_score: 0.9854
th: 0.740	 tp: 978	 tn: 5933	fp: 10	fn: 21	 prec: 0.9899 	 f1_score: 0.9844
th: 0.750	 tp: 977	 tn: 5933	fp: 10	fn: 22	 prec: 0.9899 	 f1_score: 0.9839
th: 0.760	 tp: 976	 tn: 5933	fp: 10	fn: 23	 prec: 0.9899 	 f1_score: 0.9834
th: 0.770	 tp: 975	 tn: 5933	fp: 10	fn: 24	 prec: 0.9898 	 f1_score: 0.9829
th: 0.780	 tp: 975	 tn: 5933	fp: 10	fn: 24	 prec: 0.9898 	 f1_score: 0.9829
th: 0.790	 tp: 975	 tn: 5933	fp: 10	fn: 24	 prec: 0.9898 	 f1_score: 0.9829
th: 0.800	 tp: 975	 tn: 5934	fp: 9	fn: 24	 prec: 0.9909 	 f1_score: 0.9834
th: 0.810	 tp: 974	 tn: 5934	fp: 9	fn: 25	 prec: 0.9908 	 f1_score: 0.9828
th: 0.820	 tp: 973	 tn: 5934	fp: 9	fn: 26	 prec: 0.9908 	 f1_score: 0.9823
th: 0.830	 tp: 972	 tn: 5934	fp: 9	fn: 27	 prec: 0.9908 	 f1_score: 0.9818
th: 0.840	 tp: 972	 tn: 5934	fp: 9	fn: 27	 prec: 0.9908 	 f1_score: 0.9818
th: 0.850	 tp: 972	 tn: 5934	fp: 9	fn: 27	 prec: 0.9908 	 f1_score: 0.9818
th: 0.860	 tp: 971	 tn: 5934	fp: 9	fn: 28	 prec: 0.9908 	 f1_score: 0.9813
th: 0.870	 tp: 971	 tn: 5934	fp: 9	fn: 28	 prec: 0.9908 	 f1_score: 0.9813
th: 0.880	 tp: 971	 tn: 5935	fp: 8	fn: 28	 prec: 0.9918 	 f1_score: 0.9818
th: 0.890	 tp: 970	 tn: 5935	fp: 8	fn: 29	 prec: 0.9918 	 f1_score: 0.9813
th: 0.900	 tp: 968	 tn: 5935	fp: 8	fn: 31	 prec: 0.9918 	 f1_score: 0.9803
th: 0.910	 tp: 966	 tn: 5935	fp: 8	fn: 33	 prec: 0.9918 	 f1_score: 0.9792
th: 0.920	 tp: 963	 tn: 5935	fp: 8	fn: 36	 prec: 0.9918 	 f1_score: 0.9777
th: 0.930	 tp: 963	 tn: 5935	fp: 8	fn: 36	 prec: 0.9918 	 f1_score: 0.9777
th: 0.940	 tp: 963	 tn: 5935	fp: 8	fn: 36	 prec: 0.9918 	 f1_score: 0.9777
th: 0.950	 tp: 958	 tn: 5937	fp: 6	fn: 41	 prec: 0.9938 	 f1_score: 0.9761
th: 0.960	 tp: 957	 tn: 5937	fp: 6	fn: 42	 prec: 0.9938 	 f1_score: 0.9755
th: 0.970	 tp: 949	 tn: 5939	fp: 4	fn: 50	 prec: 0.9958 	 f1_score: 0.9723
th: 0.980	 tp: 938	 tn: 5939	fp: 4	fn: 61	 prec: 0.9958 	 f1_score: 0.9665
th: 0.990	 tp: 895	 tn: 5939	fp: 4	fn: 104	 prec: 0.9956 	 f1_score: 0.9431

In [102]:
with open('XGB_best_model_big.pkl', 'wb') as file:
    pickle.dump(bst, file)

# thr = 0.970
# thr = 0.500 (bad precision = 0.9890)
# 0.640

# Classic Random Forest model

In [104]:
import optuna
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 1, 100)
    max_depth = trial.suggest_int('max_depth', 2, 30)
    min_samples_split = trial.suggest_int('min_samples_split', 4, 20)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 4, 20)

    # Create a RandomForest model
    clf = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        random_state=42
    )

    # Perform cross validation
    scores = cross_val_score(clf, X_train, y_train, cv=5, scoring='roc_auc')

    # Optuna aims to minimize the objective, hence we negate the accuracy
    return np.mean(scores)

In [105]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)

[I 2026-03-15 22:25:58,498] A new study created in memory with name: no-name-11b1eef8-3933-44b3-9c9d-7ed2d76ee0a8
[I 2026-03-15 22:26:00,429] Trial 0 finished with value: 0.9871548986127431 and parameters: {'n_estimators': 11, 'max_depth': 19, 'min_samples_split': 20, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.9871548986127431.
[I 2026-03-15 22:26:12,801] Trial 1 finished with value: 0.990717087221476 and parameters: {'n_estimators': 77, 'max_depth': 25, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 1 with value: 0.990717087221476.
[I 2026-03-15 22:26:19,181] Trial 2 finished with value: 0.9906169428112046 and parameters: {'n_estimators': 46, 'max_depth': 11, 'min_samples_split': 12, 'min_samples_leaf': 7}. Best is trial 1 with value: 0.990717087221476.
[I 2026-03-15 22:26:33,337] Trial 3 finished with value: 0.990236973866252 and parameters: {'n_estimators': 94, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 10}. Best is trial 1 with value: 0.990717087221476.
[I 2026-03-15 22:26:34,757] Trial 4 finished with value: 0.9857409209479508 and parameters: {'n_estimators': 39, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 20}. Best is trial 1 with value: 0.990717087221476.
[I 2026-03-15 22:26:34,955] Trial 5 finished with value: 0.9723036443738138 and parameters: {'n_estimators': 3, 'max_depth': 6, 'min_samples_split': 17, 'min_samples_leaf': 6}. Best is trial 1 with value: 0.990717087221476.
[I 2026-03-15 22:26:37,929] Trial 6 finished with value: 0.9897953167600981 and parameters: {'n_estimators': 48, 'max_depth': 7, 'min_samples_split': 17, 'min_samples_leaf': 7}. Best is trial 1 with value: 0.990717087221476.
[I 2026-03-15 22:26:39,319] Trial 7 finished with value: 0.9778296492182934 and parameters: {'n_estimators': 69, 'max_depth': 3, 'min_samples_split': 16, 'min_samples_leaf': 11}. Best is trial 1 with value: 0.990717087221476.
[I 2026-03-15 22:26:50,349] Trial 8 finished with value: 0.9909103925883749 and parameters: {'n_estimators': 86, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 5}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:27:03,885] Trial 9 finished with value: 0.9894748517146773 and parameters: {'n_estimators': 92, 'max_depth': 22, 'min_samples_split': 8, 'min_samples_leaf': 18}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:27:16,245] Trial 10 finished with value: 0.9893975863261444 and parameters: {'n_estimators': 66, 'max_depth': 29, 'min_samples_split': 5, 'min_samples_leaf': 14}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:27:33,208] Trial 11 finished with value: 0.9882830041052791 and parameters: {'n_estimators': 76, 'max_depth': 30, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:27:45,135] Trial 12 finished with value: 0.9900533063070514 and parameters: {'n_estimators': 83, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 9}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:27:54,229] Trial 13 finished with value: 0.9905899561647228 and parameters: {'n_estimators': 63, 'max_depth': 24, 'min_samples_split': 13, 'min_samples_leaf': 13}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:28:08,185] Trial 14 finished with value: 0.990809904701314 and parameters: {'n_estimators': 98, 'max_depth': 14, 'min_samples_split': 11, 'min_samples_leaf': 8}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:28:20,515] Trial 15 finished with value: 0.9897809351170663 and parameters: {'n_estimators': 98, 'max_depth': 12, 'min_samples_split': 12, 'min_samples_leaf': 9}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:28:24,708] Trial 16 finished with value: 0.9903320788569333 and parameters: {'n_estimators': 32, 'max_depth': 16, 'min_samples_split': 14, 'min_samples_leaf': 16}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:28:32,743] Trial 17 finished with value: 0.9900029313316654 and parameters: {'n_estimators': 86, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:28:40,861] Trial 18 finished with value: 0.9902184501501271 and parameters: {'n_estimators': 58, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 8}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:28:55,864] Trial 19 finished with value: 0.9892248023780201 and parameters: {'n_estimators': 99, 'max_depth': 19, 'min_samples_split': 11, 'min_samples_leaf': 11}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:28:56,286] Trial 20 finished with value: 0.9720394708182007 and parameters: {'n_estimators': 22, 'max_depth': 2, 'min_samples_split': 19, 'min_samples_leaf': 8}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:29:08,540] Trial 21 finished with value: 0.9905691907151917 and parameters: {'n_estimators': 80, 'max_depth': 25, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:29:19,920] Trial 22 finished with value: 0.988765513862026 and parameters: {'n_estimators': 75, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 5}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:29:28,401] Trial 23 finished with value: 0.9903852887859985 and parameters: {'n_estimators': 89, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:29:37,190] Trial 24 finished with value: 0.9895156765190167 and parameters: {'n_estimators': 56, 'max_depth': 27, 'min_samples_split': 10, 'min_samples_leaf': 4}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:29:47,795] Trial 25 finished with value: 0.9889642537248784 and parameters: {'n_estimators': 72, 'max_depth': 21, 'min_samples_split': 13, 'min_samples_leaf': 8}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:29:59,185] Trial 26 finished with value: 0.989312111962952 and parameters: {'n_estimators': 84, 'max_depth': 14, 'min_samples_split': 4, 'min_samples_leaf': 10}. Best is trial 8 with value: 0.9909103925883749.
[I 2026-03-15 22:30:08,985] Trial 27 finished with value: 0.9911142273590441 and parameters: {'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 7}. Best is trial 27 with value: 0.9911142273590441.
[I 2026-03-15 22:30:17,653] Trial 28 finished with value: 0.9907246559187192 and parameters: {'n_estimators': 98, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 13}. Best is trial 27 with value: 0.9911142273590441.
[I 2026-03-15 22:30:31,152] Trial 29 finished with value: 0.9908175739010334 and parameters: {'n_estimators': 91, 'max_depth': 15, 'min_samples_split': 11, 'min_samples_leaf': 5}. Best is trial 27 with value: 0.9911142273590441.
[I 2026-03-15 22:30:33,559] Trial 30 finished with value: 0.9840190506875184 and parameters: {'n_estimators': 90, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 27 with value: 0.9911142273590441.
[I 2026-03-15 22:30:48,156] Trial 31 finished with value: 0.9899591476741966 and parameters: {'n_estimators': 100, 'max_depth': 14, 'min_samples_split': 11, 'min_samples_leaf': 5}. Best is trial 27 with value: 0.9911142273590441.
[I 2026-03-15 22:31:02,671] Trial 32 finished with value: 0.9911880661894656 and parameters: {'n_estimators': 92, 'max_depth': 16, 'min_samples_split': 11, 'min_samples_leaf': 7}. Best is trial 32 with value: 0.9911880661894656.
[I 2026-03-15 22:31:13,532] Trial 33 finished with value: 0.9904817346847473 and parameters: {'n_estimators': 90, 'max_depth': 11, 'min_samples_split': 13, 'min_samples_leaf': 7}. Best is trial 32 with value: 0.9911880661894656.
[I 2026-03-15 22:31:25,298] Trial 34 finished with value: 0.9896298148195889 and parameters: {'n_estimators': 79, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 5}. Best is trial 32 with value: 0.9911880661894656.
[I 2026-03-15 22:31:30,904] Trial 35 finished with value: 0.9909293827241035 and parameters: {'n_estimators': 93, 'max_depth': 7, 'min_samples_split': 11, 'min_samples_leaf': 7}. Best is trial 32 with value: 0.9911880661894656.
[I 2026-03-15 22:31:34,937] Trial 36 finished with value: 0.9878860787547008 and parameters: {'n_estimators': 82, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 7}. Best is trial 32 with value: 0.9911880661894656.
[I 2026-03-15 22:31:42,071] Trial 37 finished with value: 0.9908682505868998 and parameters: {'n_estimators': 94, 'max_depth': 8, 'min_samples_split': 14, 'min_samples_leaf': 9}. Best is trial 32 with value: 0.9911880661894656.
[I 2026-03-15 22:31:52,635] Trial 38 finished with value: 0.9904996986663944 and parameters: {'n_estimators': 86, 'max_depth': 11, 'min_samples_split': 12, 'min_samples_leaf': 7}. Best is trial 32 with value: 0.9911880661894656.
[I 2026-03-15 22:31:55,303] Trial 39 finished with value: 0.9891644828932644 and parameters: {'n_estimators': 72, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 10}. Best is trial 32 with value: 0.9911880661894656.
[I 2026-03-15 22:32:01,250] Trial 40 finished with value: 0.9907898793288539 and parameters: {'n_estimators': 94, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 32 with value: 0.9911880661894656.
[I 2026-03-15 22:32:08,377] Trial 41 finished with value: 0.9911853946220786 and parameters: {'n_estimators': 95, 'max_depth': 8, 'min_samples_split': 14, 'min_samples_leaf': 9}. Best is trial 32 with value: 0.9911880661894656.
[I 2026-03-15 22:32:18,163] Trial 42 finished with value: 0.9914396546369926 and parameters: {'n_estimators': 93, 'max_depth': 10, 'min_samples_split': 14, 'min_samples_leaf': 6}. Best is trial 42 with value: 0.9914396546369926.
[I 2026-03-15 22:32:24,235] Trial 43 finished with value: 0.9909847096761224 and parameters: {'n_estimators': 95, 'max_depth': 7, 'min_samples_split': 16, 'min_samples_leaf': 6}. Best is trial 42 with value: 0.9914396546369926.
[I 2026-03-15 22:32:27,931] Trial 44 finished with value: 0.9880287571040343 and parameters: {'n_estimators': 95, 'max_depth': 5, 'min_samples_split': 17, 'min_samples_leaf': 6}. Best is trial 42 with value: 0.9914396546369926.
[I 2026-03-15 22:32:38,913] Trial 45 finished with value: 0.9898718791586711 and parameters: {'n_estimators': 87, 'max_depth': 12, 'min_samples_split': 16, 'min_samples_leaf': 9}. Best is trial 42 with value: 0.9914396546369926.
[I 2026-03-15 22:32:39,122] Trial 46 finished with value: 0.9615225929169254 and parameters: {'n_estimators': 8, 'max_depth': 3, 'min_samples_split': 18, 'min_samples_leaf': 11}. Best is trial 42 with value: 0.9914396546369926.
[I 2026-03-15 22:32:43,182] Trial 47 finished with value: 0.9894329552235229 and parameters: {'n_estimators': 37, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 8}. Best is trial 42 with value: 0.9914396546369926.
[I 2026-03-15 22:32:50,594] Trial 48 finished with value: 0.9907983915583685 and parameters: {'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 15, 'min_samples_leaf': 12}. Best is trial 42 with value: 0.9914396546369926.
[I 2026-03-15 22:33:01,869] Trial 49 finished with value: 0.9899329325925322 and parameters: {'n_estimators': 76, 'max_depth': 17, 'min_samples_split': 16, 'min_samples_leaf': 10}. Best is trial 42 with value: 0.9914396546369926.

In [106]:
study.best_params

{'n_estimators': 93,
 'max_depth': 10,
 'min_samples_split': 14,
 'min_samples_leaf': 6}

In [107]:
with open('RF_best_params_big.pkl', 'wb') as file:
    pickle.dump(study, file)

In [108]:
from sklearn.model_selection import train_test_split

#X_t, X_val, y_t, y_val = train_test_split(X_train, y_train, test_size=0.2)

#dt = xgb.DMatrix(X_train, label=y_train)
#dval = xgb.DMatrix(X_test, label=y_test)

params = {
          'n_estimators': study.best_params['n_estimators'],
          'max_depth': study.best_params['max_depth'],
        'min_samples_split': study.best_params['min_samples_split'],
        'min_samples_leaf': study.best_params['min_samples_leaf'],
        'random_state': 42
}

bst = RandomForestClassifier(**params).fit(X_train, y_train)

#scores = cross_val_score(bst, X_train, y_train, cv=5, scoring='accuracy')

In [109]:
X_test = csr_matrix(np.vstack(test_df['MorganFP'].values))

In [110]:
y_test = test_df['class'].values

In [111]:
bst

RandomForestClassifier(max_depth=10, min_samples_leaf=6, min_samples_split=14,
                       n_estimators=93, random_state=42)

In [112]:
from sklearn.metrics import roc_auc_score, precision_score, confusion_matrix, f1_score

y_pred = bst.predict(X_test)
auc = roc_auc_score(y_test, y_pred)
print(f'auc is {auc:.5f}')

y_pred = bst.predict_proba(X_test)[:, 1]
for th in np.arange(0.0, 1.0, 0.01):
    y_pred_binary = (y_pred > th).astype(int)
    cm = confusion_matrix(y_test, y_pred_binary)
    tp, fp, fn, tn = cm[1, 1], cm[0, 1], cm[1, 0], cm[0, 0]
    precision = precision_score(y_test, y_pred > th)
    f1 = f1_score(y_test, y_pred > th)
    print(f'th: {th:.3f}\t tp: {tp}\t tn: {tn}\tfp: {fp}\tfn: {fn}\t prec: {precision:.4f} \t f1_score: {f1:.4f}')

auc is 0.98506
th: 0.000	 tp: 999	 tn: 0	fp: 5943	fn: 0	 prec: 0.1439 	 f1_score: 0.2516
th: 0.010	 tp: 998	 tn: 3292	fp: 2651	fn: 1	 prec: 0.2735 	 f1_score: 0.4294
th: 0.020	 tp: 998	 tn: 4613	fp: 1330	fn: 1	 prec: 0.4287 	 f1_score: 0.5999
th: 0.030	 tp: 996	 tn: 5187	fp: 756	fn: 3	 prec: 0.5685 	 f1_score: 0.7241
th: 0.040	 tp: 994	 tn: 5484	fp: 459	fn: 5	 prec: 0.6841 	 f1_score: 0.8108
th: 0.050	 tp: 993	 tn: 5645	fp: 298	fn: 6	 prec: 0.7692 	 f1_score: 0.8672
th: 0.060	 tp: 992	 tn: 5751	fp: 192	fn: 7	 prec: 0.8378 	 f1_score: 0.9088
th: 0.070	 tp: 992	 tn: 5806	fp: 137	fn: 7	 prec: 0.8787 	 f1_score: 0.9323
th: 0.080	 tp: 992	 tn: 5836	fp: 107	fn: 7	 prec: 0.9026 	 f1_score: 0.9457
th: 0.090	 tp: 992	 tn: 5862	fp: 81	fn: 7	 prec: 0.9245 	 f1_score: 0.9575
th: 0.100	 tp: 990	 tn: 5877	fp: 66	fn: 9	 prec: 0.9375 	 f1_score: 0.9635
th: 0.110	 tp: 987	 tn: 5892	fp: 51	fn: 12	 prec: 0.9509 	 f1_score: 0.9691
th: 0.120	 tp: 987	 tn: 5898	fp: 45	fn: 12	 prec: 0.9564 	 f1_score: 0.9719
th: 0.130	 tp: 986	 tn: 5904	fp: 39	fn: 13	 prec: 0.9620 	 f1_score: 0.9743
th: 0.140	 tp: 986	 tn: 5911	fp: 32	fn: 13	 prec: 0.9686 	 f1_score: 0.9777
th: 0.150	 tp: 985	 tn: 5919	fp: 24	fn: 14	 prec: 0.9762 	 f1_score: 0.9811
th: 0.160	 tp: 985	 tn: 5919	fp: 24	fn: 14	 prec: 0.9762 	 f1_score: 0.9811
th: 0.170	 tp: 985	 tn: 5921	fp: 22	fn: 14	 prec: 0.9782 	 f1_score: 0.9821
th: 0.180	 tp: 984	 tn: 5921	fp: 22	fn: 15	 prec: 0.9781 	 f1_score: 0.9815
th: 0.190	 tp: 984	 tn: 5922	fp: 21	fn: 15	 prec: 0.9791 	 f1_score: 0.9820
th: 0.200	 tp: 984	 tn: 5923	fp: 20	fn: 15	 prec: 0.9801 	 f1_score: 0.9825
th: 0.210	 tp: 984	 tn: 5923	fp: 20	fn: 15	 prec: 0.9801 	 f1_score: 0.9825
th: 0.220	 tp: 982	 tn: 5924	fp: 19	fn: 17	 prec: 0.9810 	 f1_score: 0.9820
th: 0.230	 tp: 981	 tn: 5927	fp: 16	fn: 18	 prec: 0.9840 	 f1_score: 0.9830
th: 0.240	 tp: 981	 tn: 5927	fp: 16	fn: 18	 prec: 0.9840 	 f1_score: 0.9830
th: 0.250	 tp: 981	 tn: 5928	fp: 15	fn: 18	 prec: 0.9849 	 f1_score: 0.9835
th: 0.260	 tp: 981	 tn: 5928	fp: 15	fn: 18	 prec: 0.9849 	 f1_score: 0.9835
th: 0.270	 tp: 981	 tn: 5928	fp: 15	fn: 18	 prec: 0.9849 	 f1_score: 0.9835
th: 0.280	 tp: 981	 tn: 5930	fp: 13	fn: 18	 prec: 0.9869 	 f1_score: 0.9844
th: 0.290	 tp: 981	 tn: 5931	fp: 12	fn: 18	 prec: 0.9879 	 f1_score: 0.9849
th: 0.300	 tp: 980	 tn: 5931	fp: 12	fn: 19	 prec: 0.9879 	 f1_score: 0.9844
th: 0.310	 tp: 980	 tn: 5931	fp: 12	fn: 19	 prec: 0.9879 	 f1_score: 0.9844
th: 0.320	 tp: 980	 tn: 5931	fp: 12	fn: 19	 prec: 0.9879 	 f1_score: 0.9844
th: 0.330	 tp: 979	 tn: 5932	fp: 11	fn: 20	 prec: 0.9889 	 f1_score: 0.9844
th: 0.340	 tp: 979	 tn: 5932	fp: 11	fn: 20	 prec: 0.9889 	 f1_score: 0.9844
th: 0.350	 tp: 978	 tn: 5934	fp: 9	fn: 21	 prec: 0.9909 	 f1_score: 0.9849
th: 0.360	 tp: 977	 tn: 5934	fp: 9	fn: 22	 prec: 0.9909 	 f1_score: 0.9844
th: 0.370	 tp: 977	 tn: 5935	fp: 8	fn: 22	 prec: 0.9919 	 f1_score: 0.9849
th: 0.380	 tp: 977	 tn: 5936	fp: 7	fn: 22	 prec: 0.9929 	 f1_score: 0.9854
th: 0.390	 tp: 977	 tn: 5936	fp: 7	fn: 22	 prec: 0.9929 	 f1_score: 0.9854
th: 0.400	 tp: 976	 tn: 5936	fp: 7	fn: 23	 prec: 0.9929 	 f1_score: 0.9849
th: 0.410	 tp: 976	 tn: 5936	fp: 7	fn: 23	 prec: 0.9929 	 f1_score: 0.9849
th: 0.420	 tp: 975	 tn: 5936	fp: 7	fn: 24	 prec: 0.9929 	 f1_score: 0.9844
th: 0.430	 tp: 975	 tn: 5936	fp: 7	fn: 24	 prec: 0.9929 	 f1_score: 0.9844
th: 0.440	 tp: 974	 tn: 5936	fp: 7	fn: 25	 prec: 0.9929 	 f1_score: 0.9838
th: 0.450	 tp: 973	 tn: 5937	fp: 6	fn: 26	 prec: 0.9939 	 f1_score: 0.9838
th: 0.460	 tp: 973	 tn: 5937	fp: 6	fn: 26	 prec: 0.9939 	 f1_score: 0.9838
th: 0.470	 tp: 972	 tn: 5937	fp: 6	fn: 27	 prec: 0.9939 	 f1_score: 0.9833
th: 0.480	 tp: 972	 tn: 5937	fp: 6	fn: 27	 prec: 0.9939 	 f1_score: 0.9833
th: 0.490	 tp: 972	 tn: 5938	fp: 5	fn: 27	 prec: 0.9949 	 f1_score: 0.9838
th: 0.500	 tp: 970	 tn: 5938	fp: 5	fn: 29	 prec: 0.9949 	 f1_score: 0.9828
th: 0.510	 tp: 969	 tn: 5938	fp: 5	fn: 30	 prec: 0.9949 	 f1_score: 0.9823
th: 0.520	 tp: 968	 tn: 5938	fp: 5	fn: 31	 prec: 0.9949 	 f1_score: 0.9817
th: 0.530	 tp: 968	 tn: 5938	fp: 5	fn: 31	 prec: 0.9949 	 f1_score: 0.9817
th: 0.540	 tp: 966	 tn: 5938	fp: 5	fn: 33	 prec: 0.9949 	 f1_score: 0.9807
th: 0.550	 tp: 966	 tn: 5938	fp: 5	fn: 33	 prec: 0.9949 	 f1_score: 0.9807
th: 0.560	 tp: 963	 tn: 5938	fp: 5	fn: 36	 prec: 0.9948 	 f1_score: 0.9792
th: 0.570	 tp: 959	 tn: 5938	fp: 5	fn: 40	 prec: 0.9948 	 f1_score: 0.9771
th: 0.580	 tp: 952	 tn: 5938	fp: 5	fn: 47	 prec: 0.9948 	 f1_score: 0.9734
th: 0.590	 tp: 948	 tn: 5938	fp: 5	fn: 51	 prec: 0.9948 	 f1_score: 0.9713
th: 0.600	 tp: 947	 tn: 5938	fp: 5	fn: 52	 prec: 0.9947 	 f1_score: 0.9708
th: 0.610	 tp: 945	 tn: 5938	fp: 5	fn: 54	 prec: 0.9947 	 f1_score: 0.9697
th: 0.620	 tp: 942	 tn: 5938	fp: 5	fn: 57	 prec: 0.9947 	 f1_score: 0.9681
th: 0.630	 tp: 942	 tn: 5938	fp: 5	fn: 57	 prec: 0.9947 	 f1_score: 0.9681
th: 0.640	 tp: 941	 tn: 5938	fp: 5	fn: 58	 prec: 0.9947 	 f1_score: 0.9676
th: 0.650	 tp: 941	 tn: 5938	fp: 5	fn: 58	 prec: 0.9947 	 f1_score: 0.9676
th: 0.660	 tp: 941	 tn: 5938	fp: 5	fn: 58	 prec: 0.9947 	 f1_score: 0.9676
th: 0.670	 tp: 941	 tn: 5938	fp: 5	fn: 58	 prec: 0.9947 	 f1_score: 0.9676
th: 0.680	 tp: 939	 tn: 5938	fp: 5	fn: 60	 prec: 0.9947 	 f1_score: 0.9665
th: 0.690	 tp: 937	 tn: 5938	fp: 5	fn: 62	 prec: 0.9947 	 f1_score: 0.9655
th: 0.700	 tp: 934	 tn: 5938	fp: 5	fn: 65	 prec: 0.9947 	 f1_score: 0.9639
th: 0.710	 tp: 932	 tn: 5938	fp: 5	fn: 67	 prec: 0.9947 	 f1_score: 0.9628
th: 0.720	 tp: 932	 tn: 5938	fp: 5	fn: 67	 prec: 0.9947 	 f1_score: 0.9628
th: 0.730	 tp: 929	 tn: 5938	fp: 5	fn: 70	 prec: 0.9946 	 f1_score: 0.9612
th: 0.740	 tp: 926	 tn: 5938	fp: 5	fn: 73	 prec: 0.9946 	 f1_score: 0.9596
th: 0.750	 tp: 922	 tn: 5938	fp: 5	fn: 77	 prec: 0.9946 	 f1_score: 0.9574
th: 0.760	 tp: 919	 tn: 5938	fp: 5	fn: 80	 prec: 0.9946 	 f1_score: 0.9558
th: 0.770	 tp: 911	 tn: 5938	fp: 5	fn: 88	 prec: 0.9945 	 f1_score: 0.9514
th: 0.780	 tp: 906	 tn: 5938	fp: 5	fn: 93	 prec: 0.9945 	 f1_score: 0.9487
th: 0.790	 tp: 900	 tn: 5938	fp: 5	fn: 99	 prec: 0.9945 	 f1_score: 0.9454
th: 0.800	 tp: 895	 tn: 5938	fp: 5	fn: 104	 prec: 0.9944 	 f1_score: 0.9426
th: 0.810	 tp: 891	 tn: 5938	fp: 5	fn: 108	 prec: 0.9944 	 f1_score: 0.9404
th: 0.820	 tp: 880	 tn: 5939	fp: 4	fn: 119	 prec: 0.9955 	 f1_score: 0.9347
th: 0.830	 tp: 868	 tn: 5939	fp: 4	fn: 131	 prec: 0.9954 	 f1_score: 0.9278
th: 0.840	 tp: 858	 tn: 5939	fp: 4	fn: 141	 prec: 0.9954 	 f1_score: 0.9221
th: 0.850	 tp: 851	 tn: 5940	fp: 3	fn: 148	 prec: 0.9965 	 f1_score: 0.9185
th: 0.860	 tp: 834	 tn: 5940	fp: 3	fn: 165	 prec: 0.9964 	 f1_score: 0.9085
th: 0.870	 tp: 823	 tn: 5940	fp: 3	fn: 176	 prec: 0.9964 	 f1_score: 0.9019
th: 0.880	 tp: 809	 tn: 5940	fp: 3	fn: 190	 prec: 0.9963 	 f1_score: 0.8934
th: 0.890	 tp: 790	 tn: 5940	fp: 3	fn: 209	 prec: 0.9962 	 f1_score: 0.8817
th: 0.900	 tp: 770	 tn: 5940	fp: 3	fn: 229	 prec: 0.9961 	 f1_score: 0.8691
th: 0.910	 tp: 753	 tn: 5940	fp: 3	fn: 246	 prec: 0.9960 	 f1_score: 0.8581
th: 0.920	 tp: 735	 tn: 5940	fp: 3	fn: 264	 prec: 0.9959 	 f1_score: 0.8463
th: 0.930	 tp: 696	 tn: 5940	fp: 3	fn: 303	 prec: 0.9957 	 f1_score: 0.8198
th: 0.940	 tp: 640	 tn: 5940	fp: 3	fn: 359	 prec: 0.9953 	 f1_score: 0.7795
th: 0.950	 tp: 586	 tn: 5940	fp: 3	fn: 413	 prec: 0.9949 	 f1_score: 0.7380
th: 0.960	 tp: 522	 tn: 5941	fp: 2	fn: 477	 prec: 0.9962 	 f1_score: 0.6855
th: 0.970	 tp: 460	 tn: 5941	fp: 2	fn: 539	 prec: 0.9957 	 f1_score: 0.6297
th: 0.980	 tp: 343	 tn: 5943	fp: 0	fn: 656	 prec: 1.0000 	 f1_score: 0.5112
th: 0.990	 tp: 212	 tn: 5943	fp: 0	fn: 787	 prec: 1.0000 	 f1_score: 0.3501

In [113]:
with open('RF_best_model_big.pkl', 'wb') as file:
    pickle.dump(bst, file)

In [117]:
test_df['class'].value_counts()

class
0    5943
1     999
Name: count, dtype: int64

In [115]:
# thr = 0.970
# thr = 0.5

In [ ]:
#